'use strict';
const G=window.Blackthorn,$=id=>document.getElementById(id),storageKey='astra-blackthorn-v2';
let state=null,renderedLogEntries=0;
function validClassicState(value){return !!(value&&value.version===2&&G.classes[value.cls]&&(G.scenes[value.scene]||value.end)&&typeof value.name==='string'&&value.name.length<=30&&Array.isArray(value.log)&&value.log.length<=100&&value.log.every(entry=>entry&&typeof entry.text==='string')&&Array.isArray(value.flags)&&Array.isArray(value.journal)&&Number.isFinite(value.hp)&&Number.isFinite(value.maxHp)&&value.hp>=0&&value.hp<=value.maxHp&&Number.isFinite(value.potions)&&Number.isFinite(value.gold)&&(!value.enemy||(typeof value.enemy.name==='string'&&Number.isFinite(value.enemy.hp)&&['guard','drowned','boss'].includes(value.enemy.kind))))}
function loadSavedState(){let raw=null;try{raw=localStorage.getItem(storageKey);if(!raw)return null;const parsed=JSON.parse(raw);if(validClassicState(parsed))return parsed}catch{}if(raw)try{localStorage.removeItem(storageKey)}catch{}return null}
state=loadSavedState();
function appendLog(){
  const log=$('story'),hadEntries=renderedLogEntries>0,wasNearBottom=log.scrollHeight-log.scrollTop-log.clientHeight<90,needsReset=renderedLogEntries>state.log.length||renderedLogEntries===0;
  if(needsReset){log.replaceChildren();renderedLogEntries=0}
  for(const entry of state.log.slice(renderedLogEntries)){const wrapper=document.createElement('div');wrapper.className='entry '+entry.kind;const heading=document.createElement('h4');heading.textContent=entry.title;const paragraph=document.createElement('p');paragraph.textContent=entry.text;wrapper.append(heading,paragraph);log.append(wrapper)}
  renderedLogEntries=state.log.length;if(wasNearBottom||!hadEntries)log.scrollTop=log.scrollHeight;
}
function renderStats(character){$('stats').replaceChildren();for(const [ability,modifier] of Object.entries(character.stats)){const wrapper=document.createElement('div'),value=document.createElement('b');wrapper.textContent=ability;value.textContent=(modifier>=0?'+':'')+modifier;wrapper.append(value);$('stats').append(wrapper)}}
function renderJournal(){$('journal').replaceChildren();for(const text of state.journal){const item=document.createElement('li');item.textContent=text;$('journal').append(item)}}
function renderChoices(){$('choices').replaceChildren();G.options(state).forEach((option,index)=>{const control=document.createElement('button'),hint=document.createElement('small');control.textContent=`${index+1}. ${option.label}`;hint.textContent=option.hint;control.append(hint);control.onclick=()=>run(option.id);$('choices').append(control)});if(state.end){const restart=document.createElement('button');restart.className='primary';restart.textContent='Begin another adventure';restart.onclick=newGame;$('choices').append(restart)}}
function persist(){try{localStorage.setItem(storageKey,JSON.stringify(state));$('savestatus').textContent='PROGRESS SAVED ON THIS DEVICE'}catch{$('savestatus').textContent='SAVE UNAVAILABLE · KEEP THIS TAB OPEN'}}
function render(){const playing=!!state;$('creation').hidden=playing;$('game').hidden=!playing;if(!playing)return;const character=G.classes[state.cls];$('heroName').textContent=state.name;$('heroClass').textContent=`LEVEL 2 ${character.name.toUpperCase()} · ${character.weapon}`;$('hp').textContent=`${state.hp} / ${state.maxHp}`;$('ac').textContent=state.ac;$('health').style.width=Math.max(0,Math.min(100,state.hp/state.maxHp*100))+'%';renderStats(character);$('pack').textContent=`${state.potions} healing potions · ${state.gold} gold`+(state.cls==='wizard'?` · ${state.slots}/3 spell slots`:'');$('abilities').textContent=character.ability;renderJournal();$('chapter').textContent=state.end||G.scenes[state.scene].title;$('chapterNo').textContent=state.enemy?'ROLL INITIATIVE':G.scenes[state.scene]?.chapter.split(' / ')[0]||'EPILOGUE';appendLog();$('enemy').hidden=!state.enemy;$('enemy').textContent=state.enemy?`${state.enemy.name} · ${state.enemy.hp} / ${state.enemy.maxHp} HP · AC ${state.enemy.ac}`:'';$('dice').textContent=state.lastRoll?state.lastRoll.n:'d20';$('roll').textContent=state.lastRoll?.text||'Your fate is unwritten.';renderChoices();$('command').hidden=!!state.end;$('potion').disabled=!!state.end||!state.potions||state.hp===state.maxHp;$('rest').disabled=!!state.end||!!state.enemy||state.rested||state.hp===state.maxHp;persist()}
function run(command){if(!state)return;if(state.log.length>=95)renderedLogEntries=0;G.act(state,command);render()}
function newGame(){if(state&&!state.end&&!confirm('Start again? Your current adventure will be replaced.'))return;state=null;renderedLogEntries=0;try{localStorage.removeItem(storageKey)}catch{}render();window.scrollTo({top:0,behavior:'smooth'})}
$('heroform').onsubmit=event=>{event.preventDefault();state=G.fresh($('name').value,new FormData(event.target).get('class'));renderedLogEntries=0;render();$('game').scrollIntoView({behavior:'smooth',block:'start'})};$('command').onsubmit=event=>{event.preventDefault();const command=$('input').value;$('input').value='';run(command)};$('potion').onclick=()=>run('potion');$('rest').onclick=()=>run('rest');$('newgame').onclick=newGame;for(const id of ['rules','credits'])$(id).onclick=()=>$('modal').showModal();$('close').onclick=()=>$('modal').close();$('modal').onclick=event=>{if(event.target===$('modal')){const rect=$('modal').getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)$('modal').close()}};render();
