'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const dist=path.resolve(__dirname,'../dist');
const read=name=>fs.readFileSync(path.join(dist,name),'utf8');
const classes={fighter:{hp:24,ac:16,slots:0,weapon:'Longsword'},rogue:{hp:18,ac:14,slots:0,weapon:'Shortbow'},wizard:{hp:14,ac:12,slots:3,weapon:'Fire Bolt'}};
const prologue='Rain beads on your cloak. Ahead, Blackthorn huddles beneath a ruined abbey. Its bell tower has no bell.\n\nThe road is yours. What do you do?';
function stateFor(cls='fighter',name='Tester',options={}){const c=classes[cls];return {version:3,id:'dom-campaign',turn:0,name,cls,origin:options.origin||'human',background:options.background||'outlander',tone:options.tone||'balanced',backstory:options.backstory||'',goal:options.goal||'',level:2,xp:0,hp:c.hp,maxHp:c.hp,ac:c.ac,slots:c.slots,potions:2,gold:10,secondWindReady:cls==='fighter',conditions:[],deathSaves:{successes:0,failures:0,stable:false,defeated:false},location:'The road to Blackthorn',time:'Dusk, first day',danger:'tense',inventory:[c.weapon,'Travelling cloak','Bedroll','Rations (3 days)',...(cls==='wizard'?['Spellbook']:[])],npcs:[],quests:['Discover why Blackthorn’s dead are walking—or choose your own road.'],places:['Blackthorn','The Hollow Marches'],exits:['Blackthorn village','Greyhaven road'],factions:['Blackthorn villagers — frightened.'],facts:['The bell rang thirteen times.'],journalEvents:['The graves opened.'],memory:'Opening memory.',history:[],prologue,narrative:prologue,suggestions:['Ask the woman','Head west','Follow the bell'],lastRoll:null,lastDamage:0}}
const response=(status,body)=>({status,ok:status>=200&&status<300,json:async()=>body});
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(fn,message){for(let i=0;i<100;i++){if(fn())return;await wait(5)}throw new Error(message)}
function browserStubs(window){window.scrollTo=()=>{};window.HTMLElement.prototype.scrollIntoView=()=>{};window.confirm=()=>true;if(window.HTMLDialogElement){window.HTMLDialogElement.prototype.showModal=function(){this.open=true};window.HTMLDialogElement.prototype.close=function(){this.open=false}}try{Object.defineProperty(window.crypto,'randomUUID',{value:()=>`00000000-0000-4000-8000-${String(Date.now()).slice(-12)}`})}catch{}}
async function openWorld(saved){
  const dom=new JSDOM(read('index.html'),{url:'http://game.test/',runScripts:'outside-only',pretendToBeVisual:true}),window=dom.window;browserStubs(window);if(saved!==undefined)window.localStorage.setItem('astra-open-world-v3',saved);
  let state=null,seq=0;window.fetch=async(url,options={})=>{if(!options.method||options.method==='GET')return response(200,{configured:true,mode:'open-world',version:3,features:['identity','journal'],build:'dom-test'});const body=JSON.parse(options.body||'{}');if(body.start===true){state=stateFor(body.cls,(body.name||'').trim()||'Rowan',body);return response(200,{state,save:'dom-save-'+(++seq)+'-abcdefghijk'})}if(/rate limit/i.test(body.action||''))return response(429,{error:'Groq is rate-limited right now. Your action has not been applied.',retryAfter:1});if(!state)return response(400,{error:'missing state'});const next=structuredClone(state),action=body.action||'';next.turn++;let narrative='The Hollow Marches answer your action.';if(/healing potions/i.test(action)){next.potions--;next.hp=Math.min(next.maxHp,next.hp+7);narrative='The potion restores your strength.'}else if(/Second Wind/i.test(action)){next.secondWindReady=false;next.hp=Math.min(next.maxHp,next.hp+8);narrative='You find another reserve of strength.'}else{next.hp=Math.min(next.hp,10);next.lastRoll={dice:[15],die:15,modifier:1,total:16,dc:12,ability:'WIS',advantage:'normal',success:true,critical:false}}next.narrative=narrative;next.time='Dusk, moments later';next.history=[...next.history,{action,narrative}].slice(-6);next.suggestions=['Continue','Look around','Speak'];next.journalEvents=[...next.journalEvents,'A new choice was made.'].slice(-18);state=next;return response(200,{state,save:'dom-save-'+(++seq)+'-abcdefghijk',resolution:{kind:'none'}})};
  window.eval(read('engine.js'));window.eval(read('state-validation.js'));window.eval(read('world.js'));await wait(0);return {dom,w:window,getState:()=>state};
}
(async()=>{
  let app=await openWorld(),{dom,w}=app,d=w.document;await until(()=>/ready/i.test(d.querySelector('#availability').textContent),'DM readiness did not render');d.querySelector('#name').value='DOM Tester';d.querySelector('#origin').value='elf';d.querySelector('#background').value='criminal';d.querySelector('#tone').value='mystery';d.querySelector('#backstory').value='Raised beside the Greyhaven docks.';d.querySelector('#goal').value='Find a lost map.';d.querySelector('input[value="fighter"]').checked=true;d.querySelector('#heroform').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>!d.querySelector('#game').hidden,'character creation did not finish');assert.equal(d.querySelector('#heroName').textContent,'DOM Tester');assert.match(d.querySelector('#identity').textContent,/Elf · Criminal · Dark mystery/);assert.equal(d.querySelector('#potion').disabled,true);assert.equal(d.querySelector('#wind').hidden,false);assert.equal(d.querySelector('#wind').disabled,true);assert.match(d.querySelector('#routes').textContent,/Greyhaven road/);
  d.querySelector('#input').value='/journal';d.querySelector('#command').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(d.querySelector('#codex').open,true,'journal command should open the codex');assert.match(d.querySelector('#codexBody').textContent,/The bell rang thirteen times/);d.querySelector('#codexClose').click();
  d.querySelector('#input').value='I examine the woman';d.querySelector('#command').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('#chapterNo').textContent.startsWith('TURN 1'),'turn did not finish');assert.match(d.querySelector('#story').textContent,/Rain beads on your cloak/,'prologue vanished after a turn');assert.match(d.querySelector('#story').textContent,/I examine the woman/);assert.equal(d.querySelector('#potion').disabled,false);assert.equal(d.querySelector('#wind').disabled,false);
  d.querySelector('#wind').click();await until(()=>d.querySelector('#chapterNo').textContent.startsWith('TURN 2'),'Second Wind turn did not finish');assert.match(d.querySelector('#pack').textContent,/Second Wind spent/);assert.equal(d.querySelector('#wind').disabled,true);const persisted=JSON.parse(w.localStorage.getItem('astra-open-world-v3'));assert.equal(persisted.state.name,'DOM Tester');assert.equal(persisted.state.origin,'elf');dom.window.close();
  app=await openWorld(JSON.stringify({state:{version:3,cls:'fighter'},save:'broken-save'}));({dom,w}=app);await wait(0);assert.equal(w.document.querySelector('#creation').hidden,false,'corrupt save should be discarded');assert.equal(w.localStorage.getItem('astra-open-world-v3'),null);dom.window.close();
  const classic=new JSDOM(read('classic.html'),{url:'http://game.test/classic.html',runScripts:'outside-only',pretendToBeVisual:true});w=classic.window;browserStubs(w);w.Math.random=()=>.99;w.eval(read('engine.js'));w.eval(read('app.js'));const classicDocument=w.document;classicDocument.querySelector('#name').value='Classic DOM';classicDocument.querySelector('#heroform').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));const choose=pattern=>{const control=[...classicDocument.querySelectorAll('#choices button')].find(item=>pattern.test(item.textContent));assert(control,'missing choice '+pattern);control.click()};choose(/Promise to find her daughter/);choose(/Read the opened graves/);choose(/Show Edrin’s token/);choose(/Lead the girl back to the gate/);choose(/Save the ledger/);choose(/Leap across the broken balustrade/);choose(/Approach the bellkeeper/);choose(/Speak the name from the ledger/);assert.equal(classicDocument.querySelector('#chapter').textContent,'THE KINDNESS OF A NAME');assert.match(classicDocument.querySelector('#story').textContent,/ADVENTURE COMPLETE/);classic.window.close();
  console.log('DOM playtest passed: validated creation, codex commands, resources, turns, persistence, corrupt-save recovery and full classic peaceful route.');
})().catch(error=>{console.error(error);process.exit(1)});
